
class Config:
    Sector = [
        "Food",
        "Agriculture",
        "Clothing",
        "Construction",
        "Health",
        "Services",
        "Retail",
        "Arts",
        "Housing",
        "Transportation",
        "Manufacturing",
        "Entertainment",
        "Wholesale",
        "Education",
        "Personal Use"
    ]
    Activity = [
        "Butcher Shop",
        "Food Production/Sales",
        "Animal Sales",
        "Clothing Sales",
        "Restaurant",
        "Fish Selling",
        "Cereals",
        "Bricks",
        "Livestock",
        "Pharmacy",
        "Dairy",
        "Secretarial Services",
        "Grocery Store",
        "Carpentry",
        "General Store",
        "Bakery",
        "Used Clothing",
        "Pigs",
        "Beauty Salon",
        "Home Products Sales",
        "Crafts",
        "Tailoring",
        "Farming",
        "Poultry",
        "Construction Supplies",
        "Bicycle Repair",
        "Fishing",
        "Farm Supplies",
        "Cobbler",
        "Electrician",
        "Construction",
        "Retail",
        "Cosmetics Sales",
        "Sewing",
        "Shoe Sales",
        "Cheese Making",
        "Barber Shop",
        "Printing",
        "Party Supplies",
        "Services",
        "Personal Housing Expenses",
        "Transportation",
        "Photography",
        "Taxi",
        "Traveling Sales",
        "Phone Accessories",
        "Furniture Making",
        "Office Supplies",
        "Sporting Good Sales",
        "Veterinary Sales",
        "Machine Shop",
        "Electronics Sales",
        "Paper Sales",
        "Electronics Repair",
        "Water Distribution",
        "Land Rental",
        "Cement",
        "Cattle",
        "Phone Use Sales",
        "Catering",
        "Musical Instruments",
        "Vehicle Repairs",
        "Health",
        "Patchwork",
        "Charcoal Sales",
        "Computers",
        "Food Market",
        "Blacksmith",
        "Decorations Sales",
        "Metal Shop",
        "Plastics Sales",
        "Bicycle Sales",
        "Laundry",
        "Cafe",
        "Musical Performance",
        "Soft Drinks",
        "Textiles",
        "Dental",
        "Perfumes",
        "Milk Sales",
        "Motorcycle Transport",
        "Quarrying",
        "Air Conditioning",
        "Medical Clinic",
        "Fuel/Firewood",
        "Agriculture",
        "Arts",
        "Utilities",
        "Pub",
        "Manufacturing",
        "Bookstore",
        "Phone Repair",
        "Mobile Phones",
        "Timber Sales",
        "Hardware",
        "Food",
        "Child Care",
        "Electrical Goods",
        "Tourism",
        "Religious Articles",
        "Auto Repair",
        "Recycling",
        "Spare Parts",
        "Personal Products Sales",
        "Natural Medicines",
        "Goods Distribution",
        "Weaving",
        "Souvenir Sales",
        "Embroidery",
        "Well digging",
        "Music Discs & Tapes",
        "Motorcycle Repair",
        "Rickshaw",
        "Primary/secondary school costs",
        "Hotel",
        "Liquor Store / Off-License",
        "Bookbinding",
        "Call Center",
        "Movie Tapes & DVDs",
        "Waste Management",
        "Film",
        "Knitting",
        "Fruits & Vegetables",
        "Jewelry",
        "Cloth & Dressmaking Supplies",
        "Upholstery",
        "Internet Cafe",
        "Personal Purchases",
        "Games",
        "Entertainment",
        "Education provider",
        "Flowers",
        "Wholesale",
        "Clothing",
        "Food Stall",
        "Machinery Rental",
        "Balut-Making",
        "Vehicle",
        "Funeral Expenses",
        "Property",
        "Home Appliances",
        "Personal Medical Expenses",
        "Renewable Energy Products",
        "Recycled Materials",
        "Wedding Expenses",
        "Home Energy",
        "Consumer Goods",
        "Used Shoes",
        "Higher education costs"
    ]
    Country = [
        "Uganda",
        "Tanzania",
        "Kenya",
        "Gaza",
        "Bulgaria",
        "Senegal",
        "Nicaragua",
        "Honduras",
        "Ecuador",
        "Cambodia",
        "Samoa",
        "Mexico",
        "Moldova",
        "Nigeria",
        "Togo",
        "Ghana",
        "Mozambique",
        "Azerbaijan",
        "Ukraine",
        "Afghanistan",
        "Indonesia",
        "Cameroon",
        "Dominican Republic",
        "The Democratic Republic of the Congo",
        "Tajikistan",
        "Vietnam",
        "Bolivia",
        "Haiti",
        "Cote D'Ivoire",
        "Guatemala",
        "Iraq",
        "Sierra Leone",
        "Paraguay",
        "Peru",
        "Pakistan",
        "Nepal",
        "Lebanon",
        "El Salvador",
        "Bosnia and Herzegovina",
        "Benin",
        "Mali",
        "South Sudan",
        "Rwanda",
        "Philippines",
        "Palestine",
        "Mongolia",
        "Costa Rica",
        "United States",
        "Kyrgyzstan",
        "Liberia",
        "Armenia",
        "Colombia",
        "Chile",
        "Sri Lanka",
        "Burundi",
        "Congo",
        "Jordan",
        "South Africa",
        "Israel",
        "Georgia",
        "Zimbabwe",
        "Burkina Faso",
        "Turkey",
        "Yemen",
        "Zambia",
        "Kosovo",
        "Albania",
        "Timor-Leste",
        "Belize"
    ]
    Town = [
        "Rare_Town",
        "Managua",
        "Danli",
        "Tegucigalpa",
        "Guayaquil",
        "Kampala",
        "Phnom Penh City",
        "Dar es Salaam",
        "Kandal Province",
        "Kiambu",
        "Vailele",
        "Monterrey",
        "Nuevo Laredo",
        "Linares",
        "Escobedo, N. L.",
        "Apodaca, N. L.",
        "Yucatán",
        "Mérida, Yucatán",
        "Pedro Escobedo, Querétaro",
        "Tampico, Tamaulipas",
        "Guadalupe, Nuevo Leon",
        "Santa Catarina, Nuevo Leon",
        "Benin City",
        "Victoria, Tamaulipas",
        "Lomé",
        "Aného",
        "Nairobi",
        "Nakuru",
        "Kisumu",
        "Embu",
        "Kakamega",
        "Catembe, Maputo, Mozambique",
        "Boane, Maputo",
        "Monclova,Coahuila",
        "Acuna",
        "Tsévié",
        "Sekondi-Takoradi",
        "Cadereyta, Nuevo León, México",
        "Sumgayit city",
        "Accra",
        "Fizuli district",
        "Zaporozhye",
        "Absheron region",
        "Baku, city",
        "Faleula",
        "Salyan region",
        "Vaitele",
        "Faleasiu",
        "Eldoret, Rift Valley",
        "Novaya Kahovka",
        "Kabul Afghanistan",
        "Melitopol",
        "Berdyansk",
        "Choluteca",
        "Nikopol",
        "Saltillo, Coahuila",
        "Tangerang",
        "Los Alcarrizos",
        "Khachmaz",
        "Baku",
        "Beylagan",
        "Agsu",
        "Kinshasa",
        "Khujand",
        "Duc Linh, Binh Thuan",
        "Ivano-Frankivsk",
        "Migori",
        "Busia",
        "Kampong Cham",
        "Machakos",
        "Kitale",
        "Malie",
        "Spitamen",
        "J.Rasulov",
        "Ham Thuan Nam",
        "Nkurankan, Yilo Krobo District",
        "Istaravshan",
        "Pavlograd",
        "La Paz",
        "Agoe",
        "San Pedro de Macorís",
        "Kostakoz",
        "Monterrey, Nuevo León",
        "Trou-du-Nord",
        "Kanibadam",
        "Isfara",
        "Hato Mayor",
        "Shama",
        "El Alto",
        "Saatli",
        "kirkuk",
        "Phnom Penh",
        "Imishli",
        "Bilasuvar",
        "Makeni",
        "Kabala",
        "Magburaka, Tonkolili",
        "Asunción",
        "Kampong Chnang province, Cambodia",
        "La Romana",
        "Kamenka-Dneprovskaya",
        "Samaná",
        "Muk Kampoul district",
        "SiemReap province",
        "Legok, Tangerang",
        "Caacupe",
        "Khsach Kandal district",
        "Carapegua",
        "Khuroson",
        "Yavan",
        "Uromi, Edo State",
        "Dushanbe",
        "Gissar",
        "Coronel Oviedo",
        "Paraguari",
        "Ita",
        "Kean Svay district",
        "Pon-Nhea Leu district",
        "Sabirabad",
        "Yamasa",
        "Puerto Plata",
        "Gafurov, Tajikistan",
        "Nghi Loc",
        "Hung Nguyen",
        "Ybycuí",
        "San Lorenzo",
        "Ta Khmao district",
        "Kandal Steung district",
        "Vahdat",
        "San Ignacio",
        "Siem Reap Province",
        "Ninh Giang",
        "Asaba, Delta State",
        "Santaní",
        "Kim Dong",
        "Prey Veng Province",
        "Villa Elisa",
        "Juliaca",
        "Encarnación",
        "Pakpattan",
        "Caaguazú",
        "Ayacucho",
        "Soc Son",
        "Ciudad del Este",
        "Luque",
        "Bokhtar",
        "Mariano R. Alonso",
        "Santo Domingo",
        "Montemorelos, Nuevo León",
        "Khachmaz region",
        "Tursun-zoda",
        "San Martín",
        "Lahore",
        "Nansana",
        "Tangal",
        "SainbuBhaishepati",
        "Thecho",
        "Santa Cruz de la Sierra",
        "Saatli town",
        "Cochabamba",
        "Callería - Ucayali",
        "Badung",
        "Hédzranawoé",
        "Quang Xuong",
        "Moyobamba - San Martin",
        "Melaya, Bali",
        "Borj Barajneh",
        "HUANCAYO",
        "TARMA",
        "PUCALLPA",
        "Tripoli",
        "Vehari",
        "Leuwiliang, Bogor",
        "Rudaki",
        "Kayunga",
        "Novomoskovsk",
        "Aley",
        "Trujillo - La Libertad",
        "Bluefields.",
        "Baalback",
        "El Seybo",
        "Saida",
        "Tyre",
        "Multan",
        "Chinandega",
        "Phuc Yen",
        "Leon",
        "Nabatieh",
        "San Martín - San Martín",
        "Tarapoto - San Martin",
        "Juanjui - San Martin",
        "Huaraz - Ancash",
        "Batambong",
        "Bekaa",
        "San Cristobal",
        "Namaacha",
        "Shahrinav",
        "Yarinacocha - Ucayali",
        "Lima",
        "Bac Ninh",
        "Lagos State",
        "Mampong",
        "Kot Radha Kishan",
        "Asht",
        "Cape Coast",
        "Arifwala",
        "Obuasi",
        "Elmina",
        "Mankessim",
        "Abdurahmon Jomi",
        "Offinsu",
        "Tema",
        "Kasoa",
        "San Martin Jilotepeque, Chimaltenango",
        "Santo Domingo Norte",
        "Raiwind",
        "Kpalimé",
        "Lugazi",
        "Adéta",
        "Rajeg, Tangerang",
        "La Libertad, La Libertad",
        "Kireka",
        "Sarajevo",
        "Ntungamo",
        "Kasubi",
        "Kyengara",
        "Nateete",
        "Mukono",
        "Fuzuli region",
        "Huarochiri",
        "Lima Norte",
        "Huaycan",
        "San Juan de Lurigancho",
        "Faisalabad",
        "Y Yen",
        "Kasur",
        "Mbeya",
        "Beirut",
        "Borewala",
        "Chichawatni",
        "Kalerwe",
        "Mwanza",
        "Mubende",
        "Cotonou Agence principale",
        "Kyela",
        "Vitarte",
        "Barcenas,Villa Nueva",
        "Ibanda",
        "Agence de Thiès",
        "Mpigi",
        "Tursunzade",
        "THIES",
        "Mbour",
        "Kampong Thom",
        "Shahrituz",
        "Kumsangir",
        "Bushenyi",
        "Agence de Ziguinchor",
        "ZIGUINCHOR",
        "Kator, Juba, Southern",
        "Buluk, Juba, Southern",
        "Siem Reap",
        "Munuki, Juba, Southern",
        "Jinja",
        "Esteli",
        "Banteay Meanchey",
        "Panjakent",
        "Pursat",
        "Chontales",
        "Mityana",
        "Adidogomé",
        "Sunyani",
        "Jebel kujur,Juba",
        "Agence de Kolda",
        "Zanzibar",
        "Tanga",
        "Atlabara,Juba,southern",
        "Morogoro",
        "Arusha",
        "Hai-gabat,Juba,southern",
        "Santiago",
        "Nkawkaw",
        "Koforidua",
        "Kisii",
        "DAKAR",
        "San Juan Sacatepèquez",
        "Jalalabad",
        "Abura",
        "Goaso",
        "Utkansoi",
        "Dj.Rasulov",
        "Totonicapan",
        "Segou",
        "Sikasso",
        "Bougouni",
        "Yunguyo-Puno",
        "J.Rumy",
        "Sa Ang, Phnom Penh",
        "Dong Anh- Ha Noi",
        "Koutiala",
        "Wome",
        "Fana ",
        "SEME-PODJI",
        "Piedras Negras",
        "Kigali",
        "Zanzibar (Mikunguni)",
        "Zanzibar (Kikwajuni)",
        "Zanzibar (Jang'ombe)",
        "Zanzibar (Melinne)",
        "Siwdo",
        "CUSCO",
        "Huancavelica",
        "Kulob",
        "Prey Chhor, Kampong Cham",
        "Mombasa",
        "Calca - Calca - Cusco",
        "Tboung Khmum District",
        "PILAR",
        "Telica",
        "Pisac - Calca - Cusco",
        "Nindiri",
        "Jilikul",
        "Masaya",
        "Puno",
        "Gonchi",
        "Kampong Chhnang",
        "Thanh Hoá",
        "Chanchamayo",
        "San Jose, Antique",
        "Sta. Josefa, Agusan del Sur",
        "Plaridel - Plaridel, Misamis Occidental",
        "Ilagan",
        "Surallah, South Cotabato",
        "Bint Jbeil",
        "Sto Niño, South Cotabato",
        "Plaridel-Lopez Jaena, Misamis Occidental",
        "Calamba - Baliangao, Misamis Occidental",
        "Calamba, Misamis Occidental",
        "Oroquieta-Misamis Occidental ",
        "Dipolog City",
        "Bunawan, Agusan Del Sur",
        "Hamtic, Antique",
        "Jauja",
        "Chinchero - Urubamba - Cusco",
        "Gumbo",
        "Gudele",
        "Isabela",
        "Porto-Novo",
        "Dipolog-Dapitan City",
        "Jimenez, Misamis Occidental",
        "Zanna",
        "kyengera",
        "gaza",
        "Trento, Agusan Del Sur",
        "Ejura",
        "Thanh Hoa City",
        "Ulaanbaatar",
        "Banga, South Cotabato",
        "Ahuachapán, Ahuachapan",
        "Ibadan, Oyo State",
        "Soyapango, departamento de San Salvador",
        "Alajuela",
        "Panglao, Bohol",
        "Talibon, Bohol",
        "Bien Unido, Bohol",
        "Andahuaylillas - Quispicanchi - Cusco",
        "Ogbomoso, Oyo State",
        "Trinidad, Bohol",
        "San Miguel, Bohol",
        "Ibadan,oyo state",
        "Urcos - Quispicanchi - Cusco",
        "Urubamba - Urubamba - Cusco",
        "Anta - Anta - Cusco",
        "Santiago City, Isabela",
        "Norala, South Cotabato",
        "Tumpagon, Cagayan de Oro, Misamis Oriental",
        "Valencia City, Bukidnon",
        "Arvaiheer, Uvurhangai",
        "Takeo province",
        "Takeo",
        "Cauayan City, Isabela",
        "Waterloo",
        "Agbor, Delta state",
        "Calamba-Sapang Dalaga Misamis Occidental",
        "Tsetserleg, Arhangai",
        "Ocongate - Quispicanchi - Cusco",
        "Cachimayo - Anta - Cusco",
        "Oroquieta - Aloran",
        "Warri, Delta State",
        "Uvurhangai",
        "San Salvador,  San Salvador",
        "Baclayon, Bohol",
        "Ollantaytambo - Urubamba - Cusco",
        "Veruela, Agusan Del Sur",
        "Oda",
        "Dormaa",
        "Clarin, Misamis Occidental",
        "Clarin Misamis Occidental",
        "baguida",
        "Oroquieta City Misamis Occidental",
        "Ozamiz City",
        "Sto. Niño, Tukuran, Zamboanga del Sur",
        "Hoima",
        "Calamba Misamis Occidental",
        "Hamadoni",
        "Arkhangai",
        "Tangub City, Misamis Occidental",
        "Aurora, Zamboanga del Sur",
        "Kochkor",
        "Sapele, Delta state",
        "Wiawso",
        "Binangonan, Rizal",
        "Hohoe",
        "Tuv",
        "Iligan City, Lanao del Norte",
        "Sefwi Wiawso",
        "Pasay City",
        "Caloocan City",
        "West Point",
        "Kasese",
        "Cuenca",
        "Tokmak",
        "Payatas-B, Commonwealth, Quezon City",
        "Monrovia North",
        "Tudela, Misamis Occidental",
        "Ozamis City, Misamis  Occidental",
        "Bago, Negros Occidental",
        "Karabalta",
        "Lopez Jaena, Misamis Occidental",
        "Kilifi",
        "Silang, Cavite",
        "Naivasha",
        "Intramuros, Manila City",
        "Dasmarinas, Cavite",
        "Kangemi, Nairobi",
        "Bonifacio, Misamis Occidental",
        "South of Monrovia",
        "HINIGARAN, NEGROS OCCIDENTAL",
        "Ozamis, City, Misamis Occidental",
        "La Castellana, Negros Occidental",
        "Valladolid, Negros Occidental",
        "Mariakani",
        "Kapsabet",
        "Cadiz, Negros Occidental",
        "Manta",
        "Portoviejo",
        "Binalbagan, Negros Occidental",
        "Sevan",
        "Yerevan",
        "Thika",
        "Zitacuaro, Estado de Michoacán.",
        "Chiclayo",
        "José Leonardo Ortíz - Chiclayo",
        "Lofa Co. Northern Liberia",
        "Narok",
        "Lambayeque",
        "Escalante, Negros Occidental",
        "Mórrope - Lambayeque",
        "Camiguin",
        "Ijevan",
        "Tagbilaran, Bohol",
        "Talakag, Bukidnon",
        "Konongo",
        "Gingoog City, Misamis Oriental",
        "Agence de Diourbel",
        "Hovd",
        "Tukuran, Zamboanga Del Sur",
        "Bayanhongor",
        "Fort Portal",
        "Tosontsengel, Zavhan",
        "Granada",
        "Bayan-Ulgii",
        "Balykchi",
        "Bo",
        "Narantuul, Ulaanbaatar",
        "malindi",
        "KABARNET",
        "San Rafael",
        "Ica",
        "Thika-Town",
        "Freetown Central",
        "SANTIAGO",
        "Ongata-Rongai",
        "Kyenjojo",
        "Kitengela",
        "Chinandega El Bisne",
        "Guayaquil (Isla)",
        "Guayaquil (Paraiso)",
        "Olmos - Lambayeque",
        "El Sauce",
        "Murang'a",
        "Jogoo Road",
        "Guayaquil (Fortin)",
        "Kade",
        "Oropesa - Quispicanchi - Cusco",
        "Agence de Louga",
        "Uvs",
        "Paijan - Ascope - La Libertad",
        "Cayaltí - Chiclayo",
        "Nairobi Central",
        "Parcona",
        "Nueva Guinea, RAAS",
        "Mayoreo",
        "San Miguel, San Miguel",
        "Allada",
        "COPAINALÁ, CHIAPAS",
        "Talim Island, Binangonan Rizal",
        "huvsgul",
        "Kihihi",
        "Masindi",
        "Bayawan, Negros Oriental",
        "Barranquilla",
        "Soledad Atlàntico",
        "GMA, Cavite",
        "Hinobaan, Negros Occidental",
        "Cartagena de Indias",
        "Red Light, Paynesville",
        "Cauayan, Negros Occidental",
        "Kabankalan, Negros Occidental",
        "San Miguel",
        "litein",
        "Tanza, Cavite",
        "Malambo-Atlántico",
        "Rukungiri",
        "Nairobi East",
        "Aravan",
        "Bogotà",
        "Nkubu",
        "Nyamira",
        "Chillanes",
        "San Carlos, Negros Occidental",
        "Uzgen",
        "Monrovia South",
        "Guayaquil (Suburbio)",
        "Estefania, Amulung, Cagayan",
        "Nairobi West",
        "Guaranda",
        "Olkalou",
        "Ndunyu Njeru",
        "Kadamjai",
        "Goma, North Kivu province",
        "Bujumbura",
        "Chepén, La Libertad",
        "Bais, Negros Oriental",
        "Guayaquil (Guasmo)",
        "Tup",
        "Songinohairhan, Ulaanbaatar",
        "Kisauni",
        "Eastern Wao, Lanao del Sur",
        "Likoni",
        "Guayaquil (Orquideas)",
        "Kagadi",
        "El Transito, San Miguel",
        "Tanjay, Negros Oriental",
        "Duran (Primavera)",
        "Juticalpa, Olancho",
        "Brazzaville",
        "Chtoura",
        "Tambogrande - Piura",
        "Santander, Cebu",
        "San Francisco Gotera, Morazan",
        "Toktogul",
        "Villarrica",
        "Dalaguete, Cebu",
        "Bundibugyo",
        "Tashkomur",
        "Minglanilla, Cebu",
        "Cordova, Cebu",
        "Bogo, Cebu",
        "Compostela, Cebu",
        "San Rafael de Oriente, San Miguel",
        "Usulután",
        "Ventanas",
        "Toledo, Cebu",
        "Puerto Princesa, Palawan",
        "Brookes Point, Palawan",
        "Sansar, Ulaanbaatar",
        "Narra, Palawan",
        "Hai Gwafa, Yei",
        "Dar es Salaam, Yei",
        "Roxas Palawan",
        "Hai Mahad, Yei",
        "Jigomoni, Yei",
        "Batasan, Quezon City",
        "Khanewal",
        "Samburu",
        "Concepción",
        "Bacoor, Cavite",
        "Mwingi",
        "Matuu",
        "Reussey Keo",
        "Kracheh",
        "Tala",
        "Playas (Villamil)",
        "Jiquilisco, Usulutan",
        "Boaco",
        "Victorias, Negros Occidental",
        "Msambweni",
        "Oloitoktok",
        "Emali",
        "Akodessewa",
        "San Francisco, Agusan Del Sur",
        "Kamwenge",
        "Al-Hashmi-Amman",
        "Prey Chor",
        "Medellín",
        "Bello",
        "Kaloleni",
        "Itagui",
        "Gitega",
        "Kenema",
        "Rionegro",
        "Dangara",
        "Freetown East",
        "Curuguaty",
        "Ain",
        "Baqaa",
        "Salt",
        "Ornlong Veng",
        "Gweru",
        "Zarqa",
        "Paynesville South",
        "Congo Town",
        "Gounghin, Ouagadougou",
        "Kaya-Road-South Sudan",
        "Madaba",
        "Masvingo",
        "Ho Chi Minh City",
        "SIGNOGHIN",
        "Mwambalazi",
        "Camana",
        "Tiribe",
        "CHINCHA",
        "Nazca",
        "VEDOKO, COTONOU",
        "Airport",
        "Irbid",
        "Chwele",
        "Koidu/Kono",
        "Sana'a",
        "Pinto Alfonso Lista, Ifugao",
        "Munuki",
        "Changamwe",
        "Taguig City",
        "Battambang province, Thmor Koul district",
        "Kampong Cham province, Ponhea Krek district",
        "Kongowea",
        "Maua",
        "Battambang province, Moung Russey district",
        "Webuye",
        "Montecristi",
        "Langber Bor",
        "Dokuru bor",
        "Buchanan",
        "Air port yambio",
        "Huatusco",
        "Teshie, Accra",
        "Kampong Cham province, Dambae district",
        "Antequera, Bohol"
    ]
    FundedTime = True
    PartnerID = True
    LoanAmount = True
    LoanTerm = True

    @staticmethod
    def has(name):
        return hasattr(Config, name)

    @staticmethod
    def get(name):
        if Config.has(name):
            return getattr(Config, name)
        return None
